print("Hello, World!")
print("http://www.overthewire.org/wargames/bandit/")
print("Level 0 -> 1")
print("ssh -p 2220 bandit0@bandit.labs.overthewire.org")
print("bandit0")
print("Level 1 -> 2")
print("ssh -p 2220 bandit1@bandit.labs.overthewire.org")
print("NH2SXQwcBdpmTEzi3bvBHMM9H66vVXjL")
print("Level 2 -> 3")
print("ssh -p 2220 bandit2@bandit.labs.overthewire.org")
print("rRGizSaX8Mk1RTb1CNQoXTcYZWU6lgzi")
print("Level 3 -> 4")
print("ssh -p 2220 bandit3@bandit.labs.overthewire.org")
print("aBZ0W5EmUfAf7kHTQeOwd8bauFJ2lAiG")

